@baseUrl = https://pokeapi.co/api/v2/
@pokemonName = pikachu
@limit = 10
@offset = 40
@type = 13
@stat = 6

### Get list of 10 Pokémon
GET {{baseUrl}}/pokemon?limit={{limit}}

//example
//GET /resource?limit=10&offset=20

### Get list of 10 Pokemon with Offset
GET {{baseUrl}}/pokemon?limit={{limit}}&offset={{offset}}

### Get Pokemon
GET {{baseUrl}}/pokemon/{{pokemonName}}

### Get Head
HEAD {{baseUrl}}/pokemon/{{pokemonName}}

### Get Type
GET {{baseUrl}}/type/{{type}}/

### GET Stat
GET {{baseUrl}}/stat/{{stat}}/

### 404 - Pokemon not found
GET {{baseUrl}}/pokemon/pikachoo

### 200 - Pokemon exists
GET {{baseUrl}}/pokemon/{{pokemonName}}

### Likely 404 - Wrong endpoint path
GET {{baseUrl}}/pokemonn/{{pokemonName}}

### 405 - Method not allowed
POST {{baseUrl}}/pokemon/{{pokemonName}}
Content-Type: application/json

{
    "test": true
}

### Network error - DNS fail
GET https://pokeapi.coo/api/v2/pokemon/{{pokemonName}}

